### ISSUE TITLE
expand text extraction and / or write example on insults?

### ISSUE THREAD

**Issue by amueller** [amueller/scipy_2015_sklearn_tutorial#20]

**Comment by kastnerkyle** [comment]
I worked on 3.4 but have not done 3.5 - I can do it based on your blog or you can do it - up to you

**Comment by amueller** [comment]
Sorry I'm offline till Monday night. Maybe we should just go with the 20
news? Don't worry about it, I have a notebook on the insults.

**Comment by kastnerkyle** [comment]
OK that works for me. I will look at other sections - I did a little bit
(really just cut some stuff) for text feature extraction "methods" part.

If you would rather just use 20 news that is cool - you are the master of
the insult part so I will let you choose :D. I will go through day 2 and
see if I see anything, though I will wait til any of your changes are in
before doing anything more than take notes on what to fix.

**Comment by kastnerkyle** [comment]
thinking a bit more - is the troll detection data public or only through
Kaggle? If it is only through Kaggle we may not be able to use it

**Comment by amueller** [comment]
ok done with a very simple and small sms dataset
