### ISSUE TITLE
Add Links to YouTube Videos

### ISSUE THREAD

**Issue by RoyiAvital** [amueller/scipy_2015_sklearn_tutorial#57]
Hello,

Could you add links to YouTube videos:
- [Video - Part I](https://www.youtube.com/watch?v=80fZrVMurPM).
- [Video - Part II](https://www.youtube.com/watch?v=Ud-FsEWegmA).

Thank You.

**Comment by amueller** [comment]
Good idea. Fixed in 42e1d5439e024fda5a7def2a94a07d0f09ff8b61.
