### ISSUE TITLE
use learning_curve in 6.3

### ISSUE THREAD

**Issue by amueller** [amueller/scipy_2015_sklearn_tutorial#6]
I think we should use the learning_curve function in 6.3. But then we need to use an sklearn estimator, not polyfit.
Maybe going back to the KNN regression example of 6.2 would be good. Or we could do polynomial fitting with SVR?

**Comment by amueller** [comment]
I did that but learning curves are not great for KNN as they are a parametric model :-/ Doing polyfitting with sklearn requires a pipeline which is introduced later

**Comment by kastnerkyle** [comment]
I fixed this using SVR
