### ISSUE TITLE
cross validation

### ISSUE THREAD

**Issue by MEHWISHSABA** [amueller/scipy_2015_sklearn_tutorial#61]
E:\Anaconda folder\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
plz solve my problem

**Comment by amueller** [comment]
you should use the updated version at https://github.com/amueller/scipy-2017-sklearn/

**Comment by MEHWISHSABA** [comment]
dear sir.
i need data dictionary of the customer churn dataset

i extremely need it .because i want to know why these fields(state, area
code,phone number ,churn) are removed in customer churn dataset .so that i
will be able to get the information about dataset.
so please sir send me data dictionary as soon as possible. i will be very
thankful to you.

**Comment by amueller** [comment]
There was no churn data in this tutorial as far as I know.
